name: build
on: [push]

permissions:
  checks: write

jobs:
  build:
    runs-on: ubuntu-26.04
    strategy:
      matrix:
        BUILD_TARGET: [release]
    outputs:
      release_built: ${{ steps.set-output.outputs.release_built }}
    steps:
      - uses: actions/checkout@v7

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libopus-dev pkg-config protobuf-compiler

      - name: Build binaries in "${{ matrix.BUILD_TARGET }}" mode
        run: cargo build --profile ${{ matrix.BUILD_TARGET }} --verbose

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - uses: auguwu/clippy-action@1.5.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}

      - uses: bnjbvr/cargo-machete@main

      - name: Run tests in "${{ matrix.BUILD_TARGET }}" mode
        run: cargo test --profile ${{ matrix.BUILD_TARGET }} --verbose
